version: 2.1

orbs:
  node: circleci/node@1.1.4

only-run-on-branches: &only-run-on-branches
  branches:
    ignore:
      - main

only-run-on-main: &only-run-on-main
  branches:
    only:
      - main

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: npm
          filters:
            <<: *only-run-on-branches
      - build:
          context: npm
          publish: true
          filters:
            <<: *only-run-on-main

jobs:
  build:
    parameters:
      publish:
        type: boolean
        default: false
    docker:
      - image: circleci/node:erbium
    working_directory: ~/project
    steps:
      - checkout
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc'
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run: npm test
      - when:
          condition: <<parameters.publish>>
          steps:
            - run: npm run semantic-release
