version: 2.1

node-image: &node-image
  image: circleci/node:14.8.0
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_ACCESS_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context:
            - npm
            - github

jobs:
  build:
    docker:
      - <<: *node-image
    working_directory: ~/project
    steps:
      - checkout
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - when:
          condition:
            equal: [main, <<pipeline.git.branch>>]
          steps:
            - run: npm run semantic-release
